abpBrainExtraction <- function( img = NA, intensityTruncation=c( 0.025, 0.975, 256 ), mask=NA, weightimg=NA, usen3=FALSE )
{
# should take in a data frame to organize input data!
#BA    TMP_FILES=( $EXTRACTION_MASK_PRIOR_WARPED $EXTRACTION_WARP $EXTRACTION_INVERSE_WARP $EXTRACTION_MATRIX_OFFSET $EXTRACTION_TMP $EXTRACTION_MASK_TMP $EXTRACTION_GM $EXTRACTION_CSF $EXTRACTION_SEGMENTATION $EXTRACTION_INITIAL_AFFINE $EXTRACTION_INITIAL_AFFINE_MOVING $EXTRACTION_INITIAL_AFFINE_FIXED $EXTRACTION_LAPLACIAN $EXTRACTION_TEMPLATE_LAPLACIAN )
#BA
#BA    ## Step 1 ##
#BA    if [[ ! -f ${EXTRACTION_WARP} ]];
#BA      then

#BA      logCmd ${ANTSPATH}/ResampleImageBySpacing 3 ${EXTRACTION_TEMPLATE} ${EXTRACTION_INITIAL_AFFINE_FIXED} 4 4 4 1
#BA      logCmd ${ANTSPATH}/ResampleImageBySpacing 3 ${N4_CORRECTED_IMAGES[0]} ${EXTRACTION_INITIAL_AFFINE_MOVING} 4 4 4 1

#BA      logCmd ${ANTSPATH}/ImageMath 3 ${EXTRACTION_LAPLACIAN} Laplacian ${N4_CORRECTED_IMAGES[0]} 1.5 1
#BA      logCmd ${ANTSPATH}/ImageMath 3 ${EXTRACTION_TEMPLATE_LAPLACIAN} Laplacian ${EXTRACTION_TEMPLATE} 1.5 1

#BA      exe_initial_align="${ANTSPATH}/antsAffineInitializer ${DIMENSION} ${EXTRACTION_INITIAL_AFFINE_FIXED} ${EXTRACTION_INITIAL_AFFINE_MOVING} ${EXTRACTION_INITIAL_AFFINE} 15 0.1 0 10"
#BA      if [[ -f ${EXTRACTION_REGISTRATION_MASK} ]];
#BA        then
#BA        exe_initial_align="${exe_initial_align} ${EXTRACTION_REGISTRATION_MASK}"
#BA        fi
#BA      logCmd $exe_initial_align

#BA      basecall="${ANTS} -d ${DIMENSION} -u 1 -w [0.025,0.975] -o ${EXTRACTION_WARP_OUTPUT_PREFIX} -r ${EXTRACTION_INITIAL_AFFINE} -z 1"
#BA      if [[ -f ${EXTRACTION_REGISTRATION_MASK} ]];
#BA        then
#BA        basecall="${basecall} -x [${EXTRACTION_REGISTRATION_MASK}]"
#BA        fi
#BA      stage1="-m MI[${EXTRACTION_TEMPLATE},${N4_CORRECTED_IMAGES[0]},${ANTS_LINEAR_METRIC_PARAMS}] -c ${ANTS_LINEAR_CONVERGENCE} -t Rigid[0.1] -f 8x4x2x1 -s 4x2x1x0";
#BA      stage2="-m MI[${EXTRACTION_TEMPLATE},${N4_CORRECTED_IMAGES[0]},${ANTS_LINEAR_METRIC_PARAMS}] -c ${ANTS_LINEAR_CONVERGENCE} -t Affine[0.1] -f 8x4x2x1 -s 4x2x1x0";
#BA      stage3=" -m CC[${EXTRACTION_TEMPLATE},${N4_CORRECTED_IMAGES[0]},0.5,4] -m CC[${EXTRACTION_TEMPLATE_LAPLACIAN},${EXTRACTION_LAPLACIAN},0.5,4] -c [50x10x0,1e-9,15] -t SyN[0.1,3,0] -f 4x2x1 -s 2x1x0";

#BA      exe_brain_extraction_1="${basecall} ${stage1} ${stage2} ${stage3}"
#BA      logCmd $exe_brain_extraction_1
#BA      fi

#BA    ## Step 2 ##
#BA    exe_brain_extraction_2="${WARP} -d ${DIMENSION} -i ${EXTRACTION_PRIOR} -o ${EXTRACTION_MASK_PRIOR_WARPED} -r ${ANATOMICAL_IMAGES[0]} -n Gaussian -t [${EXTRACTION_MATRIX_OFFSET},1] -t ${EXTRACTION_INVERSE_WARP}"
#BA    logCmd $exe_brain_extraction_2

#BA    ## superstep 1b ##
#BA    logCmd ${ANTSPATH}ThresholdImage ${DIMENSION} ${EXTRACTION_MASK_PRIOR_WARPED} ${EXTRACTION_MASK_PRIOR_WARPED} 0.5 1 1 0
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} MD ${EXTRACTION_MASK_PRIOR_WARPED} 2
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} GetLargestComponent ${EXTRACTION_MASK_TMP}

#BA    ## superstep 6 ##

#BA    ATROPOS_ANATOMICAL_IMAGES_COMMAND_LINE='';
#BA    for (( i = 0; i < ${#ANATOMICAL_IMAGES[@]}; i++ ))
#BA      do
#BA      ATROPOS_ANATOMICAL_IMAGES_COMMAND_LINE="${ATROPOS_ANATOMICAL_IMAGES_COMMAND_LINE} -a ${N4_CORRECTED_IMAGES[$i]}";
#BA      done

#BA    exe_brain_extraction_3="${ATROPOS} -d ${DIMENSION} -o ${EXTRACTION_SEGMENTATION} ${ATROPOS_ANATOMICAL_IMAGES_COMMAND_LINE} -x ${EXTRACTION_MASK_TMP} -i ${ATROPOS_BRAIN_EXTRACTION_INITIALIZATION} -c ${ATROPOS_BRAIN_EXTRACTION_CONVERGENCE} -m ${ATROPOS_BRAIN_EXTRACTION_MRF} -k ${ATROPOS_BRAIN_EXTRACTION_LIKELIHOOD}"
#BA    logCmd $exe_brain_extraction_3

#BA    logCmd ${ANTSPATH}/ThresholdImage ${DIMENSION} ${EXTRACTION_SEGMENTATION} ${EXTRACTION_WM} 3 3 1 0
#BA    logCmd ${ANTSPATH}/ThresholdImage ${DIMENSION} ${EXTRACTION_SEGMENTATION} ${EXTRACTION_GM} 2 2 1 0
#BA    logCmd ${ANTSPATH}/ThresholdImage ${DIMENSION} ${EXTRACTION_SEGMENTATION} ${EXTRACTION_CSF} 1 1 1 0

#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_WM} GetLargestComponent ${EXTRACTION_WM}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_GM} GetLargestComponent ${EXTRACTION_GM}

#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_TMP} FillHoles ${EXTRACTION_GM} 2
#BA    logCmd ${ANTSPATH}MultiplyImages ${DIMENSION} ${EXTRACTION_GM} ${EXTRACTION_TMP} ${EXTRACTION_GM}

#BA    logCmd ${ANTSPATH}MultiplyImages ${DIMENSION} ${EXTRACTION_WM} 3 ${EXTRACTION_WM}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_TMP} ME ${EXTRACTION_CSF} 10

#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_GM} addtozero ${EXTRACTION_GM} ${EXTRACTION_TMP}
#BA    logCmd ${ANTSPATH}MultiplyImages ${DIMENSION} ${EXTRACTION_GM} 2 ${EXTRACTION_GM}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_SEGMENTATION} addtozero ${EXTRACTION_WM} ${EXTRACTION_GM}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_SEGMENTATION} addtozero ${EXTRACTION_SEGMENTATION} ${EXTRACTION_CSF}

#BA    ## superstep 7 ##
#BA    logCmd ${ANTSPATH}ThresholdImage ${DIMENSION} ${EXTRACTION_SEGMENTATION} ${EXTRACTION_MASK_TMP} 2 3
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} ME ${EXTRACTION_MASK_TMP} 2
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} GetLargestComponent ${EXTRACTION_MASK_TMP}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} MD ${EXTRACTION_MASK_TMP} 4
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} FillHoles ${EXTRACTION_MASK_TMP} 2
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} addtozero ${EXTRACTION_MASK_TMP} ${EXTRACTION_MASK_PRIOR_WARPED}
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} MD ${EXTRACTION_MASK_TMP} 5
#BA    logCmd ${ANTSPATH}ImageMath ${DIMENSION} ${EXTRACTION_MASK_TMP} ME ${EXTRACTION_MASK_TMP} 5

#BA    cp ${EXTRACTION_MASK_TMP} ${EXTRACTION_MASK}

#BA    logCmd ${ANTSPATH}/MultiplyImages ${DIMENSION} ${EXTRACTION_MASK} ${N4_CORRECTED_IMAGES[0]} ${EXTRACTION_BRAIN}

}
